version: "3.9"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:v1
    build:
      context: ./requirement/mariadb
      dockerfile: Dockerfile
    restart: always
    volumes:
      - DB:/var/lib/mysql
    networks:
      - my_service
    environment:
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=hanbin0127

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress:v1
    build:
      context: ./requirement/wordpress
      dockerfile: Dockerfile
    restart: always
    volumes:
      - WordPress:/var/www/wordpress
    networks:
      - my_service
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb:3306
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_DATABASE_PASS=hanbin0127
      - WORDPRESS_URL=hanbkim.42.fr
      - WORDPRESS_TITLE=hanbkim
      - WORDPRESS_ADMIN_USER=hanbkim
      - WORDPRESS_ADMIN_PASSWORD=hanbin0127
      - WORDPRESS_ADMIN_EMAIL=foo@mail.com

  nginx:
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    image: nginx:v1
    build:
      context: ./requirement/nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - WordPress:/var/www
    ports:
      - "443:443"
    networks:
      - my_service

volumes:
  DB:
  WordPress:
        
networks:
  my_service:

# secrets:


# configs:
