version: "3.9"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:v1
    build:
      context: ./requirement/mariadb
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ~/container_data/db:/var/lib/mysql
    networks:
      - my_service
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress:v1
    build:
      context: ./requirement/wordpress
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ~/container_data/wordpress:/var/www
    networks:
      - my_service
    environment:
      WORDPRESS_DATABASE_HOST: ${WORDPRESS_DATABASE_HOST}
      WORDPRESS_DATABASE_NAME: ${WORDPRESS_DATABASE_NAME}
      WORDPRESS_DATABASE_USER: ${WORDPRESS_DATABASE_USER}
      WORDPRESS_DATABASE_PASS: ${WORDPRESS_DATABASE_PASS}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USER_LOGIN: ${WORDPRESS_USER_LOGIN}
      WORDPRESS_USER_PASSWORD: ${WORDPRESS_USER_PASSWORD}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}

  nginx:
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    image: nginx:v1
    build:
      context: ./requirement/nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ~/container_data/wordpress:/var/www
    ports:
      - "443:443"
    networks:
      - my_service

networks:
  my_service:
