version: "3.9"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:v1
    build:
      context: ./requirement/mariadb
      dockerfile: Dockerfile
    restart: always
    volumes:
      - DB:/var/lib/mysql
    networks:
      - wordpress_mariadb
    environment:
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=hanbin0127

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress:v1
    build:
      context: ./requirement/wordpress
      dockerfile: Dockerfile
    restart: always
    volumes:
      - WordPress:/var/www/wordpress
    networks:
      - nginx_wordpress
      - wordpress_mariadb

  nginx:
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    image: nginx:v1
    build:
      context: ./requirement/nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - WordPress:/var/www
    ports:
      - "443:443"
    networks:
      - nginx_wordpress

volumes:
  DB:
  WordPress:
        
networks:
  nginx_wordpress:
  wordpress_mariadb:

# secrets:


# configs:
