FROM alpine:3.16

RUN apk update && apk add mariadb mariadb-client openrc

RUN mariadb-install-db --datadir=/var/lib/mysql && chown -R mysql:mysql /var/lib/mysql

RUN rc-status && touch /run/openrc/softlevel && rc-service mariadb start

WORKDIR /workspace
COPY tools/database_init.sql /workspace
COPY tools/init.sh /workspace

EXPOSE 3306

CMD ["mariadbd", "-u", "root"]
ENTRYPOINT ["sh", "init.sh"]
#CMD ["tail", "-f"]
