# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hanbkim <hanbkim@student.42seoul.kr>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/02/09 11:54:04 by hanbkim           #+#    #+#              #
#    Updated: 2023/02/09 21:04:48 by hanbkim          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = contact.cpp phonebook.cpp main.cpp mycin.cpp

NAME = book

include ../Makefile.template
